# Generated by Django 5.2.2 on 2025-06-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0002_server_current_players_server_image_server_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_until', models.DateTimeField(blank=True, null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
