# Generated by Django 5.2.2 on 2025-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_service_serverservice_robokassatransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_balance_topup',
            field=models.BooleanField(default=False),
        ),
    ]
