# Generated by Django 5.2.2 on 2025-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_service_is_balance_topup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_balance_topup',
        ),
        migrations.AddField(
            model_name='robokassatransaction',
            name='is_balance_topup',
            field=models.BooleanField(default=False),
        ),
    ]
