# Generated by Django 5.2.2 on 2025-06-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_purchasedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='listing_limit',
            field=models.IntegerField(default=0, help_text='Максимум мест (0 = без лимита)'),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.IntegerField(default=0, help_text='Порядок сортировки в листинге'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_listing',
            field=models.BooleanField(default=True),
        ),
    ]
