# Generated by Django 5.2.3 on 2025-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_service_listing_limit_service_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('boost', 'Boost'), ('color', 'Color'), ('votes', 'Голоса')], max_length=20),
        ),
    ]
