# Generated by Django 5.2.2 on 2025-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdonation',
            name='payment_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
