# Generated by Django 5.2.3 on 2025-06-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_downloadstat_purchasedservice'),
        ('servers', '0011_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdonation',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.server'),
        ),
    ]
