# Generated by Django 5.2.3 on 2025-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_manualdonation_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadstat',
            old_name='timestamp',
            new_name='downloaded_at',
        ),
        migrations.AddField(
            model_name='purchasedservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
