# Generated by Django 5.2.2 on 2025-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='current_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='server_images/'),
        ),
        migrations.AddField(
            model_name='server',
            name='map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='max_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
