# Generated by Django 5.2.2 on 2025-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_current_players_server_image_server_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
