# Generated by Django 5.2.2 on 2025-06-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='servers.server'),
        ),
    ]
