# Generated by Django 5.2.2 on 2025-06-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_vote_is_upvote_alter_vote_server'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
