# Generated by Django 5.2.2 on 2025-06-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
