# Generated by Django 5.2.3 on 2025-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='votes_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
