# Generated by Django 5.2.3 on 2025-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_votes_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='Новичок', max_length=50),
        ),
    ]
